

import NavbarMenu from "@/components/NavbarMenu";
import "./globals.css";
import 'bootstrap/dist/css/bootstrap.min.css';
import { Ubuntu } from 'next/font/google';
import NavbarFooter from "@/components/NavbarFooter";


const ubuntu = Ubuntu({
  weight: ['300', '400', '500', '700'],
  subsets: ['latin'],
});




export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={ubuntu.className}>
        <NavbarMenu/>
        {children}
        <NavbarFooter/>
      </body>
    </html>
  );
}
